# Generated by Django 3.1.7 on 2021-03-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Nurse')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Address', models.TextField()),
                ('Experience', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1)),
                ('Qualification', models.CharField(max_length=50)),
                ('WorkingDays', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('FeesPerDay', models.IntegerField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_heartCare.hospital')),
            ],
        ),
    ]
